name: Generate Documentation

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/generate-documentation.yml'
            - 'source/**.js'

jobs:
    generate:
        name: JSDoc
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

            - name: Compile Docs
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir: ./source/public/scripts
                  output_dir: ./source/docs
                  template: minami
                  front_page: ./source/README.md
                  recurse: true

            - name: Commit and Push
              uses: EndBug/add-and-commit@v7
              with:
                  default_author: github_actions
                  message: 'Update JSDoc from Github Actions (Documentation Generation)'